name: Deploy Backend to DockerHub

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-app
